workflow "Package with VSCE" {
  on = "push"
  resolves = ["VSCE: Publish"]
}

action "NPM: Install deps" {
  uses = "actions/npm@33871a7"
  args = ["install", "--unsafe-perm"]
}

action "NPM: Compile" {
  uses = "actions/npm@33871a7"
  args = "run compile"
  needs = ["NPM: Install deps"]
}

action "VSCE: Publish" {
  uses = "lannonbr/vsce-action@master"
  args = "publish -p $VSCE_TOKEN"
  needs = ["NPM: Compile"]
  secrets = ["q65epvc4npe2helwbitgvlgep62es5sw74kjt6quzjynyjclijvq"]
}
